pipeline {

    agent {
        node {
            label 'maven'
        }
    }

    options {
        skipDefaultCheckout true
    }

    stages {

        stage('Checkout') {
            steps {
                sendNotification('started', 'team@example.com')
                git branch: 'notifications',
                    url: 'https://github.com/avineo13/DO400-apps'
            }
        }

        stage('Test') {
            steps {
                dir('simple-calculator') {
                    sh './mvnw clean test'
                }
            }
        }

        stage('Check Style') {
            steps {
                dir('simple-calculator') {
                    script {
                        try {
                            sh './mvnw clean checkstyle:check'
                        } catch (Exception e) {
                            sendStageNotification('failed', 'devs@example.com')
                            unstable("Stage ${STAGE_NAME} failed!")
                        }
                    }
                }
            }
        }

    }

    post {

        failure {
            sendNotification('failed', 'team@example.com')
        }

        always {
            sendNotification('finished', 'team@example.com')
        }

    }

}

void sendNotification(String action, String email) {
    mail to: "${email}",
        subject: "Pipeline ${action}, ${currentBuild.fullDisplayName}",
        body: "The following pipeline ${action}: ${env.BUILD_URL}"
}

void sendStageNotification(String action, String email) {
    mail to: "${email}",
        subject: "${STAGE} ${action}, ${currentBuild.fullDisplayName}",
        body: "The stage ${STAGE} ${action}: ${env.BUILD_URL}"
}
