pipeline {

    agent {
        node {
            label 'maven'
        }
    }

    environment {
        APP_NAMESPACE = 'qzjkdo-recover'
    }

    stages {

        stage('Test') {

            options {
                timeout(time: 250, unit: 'SECONDS')
            }

            steps {
                dir('shopping-cart-v2') {
                    sh './mvnw clean test'
                }
            }
        }

    }

}