pipeline {

    agent {
        node {
            label 'maven'
        }
    }

    environment {
        APP_NAMESPACE = 'qzjkdo-recover'
    }

    parameters {
        string(name: 'DEPLOY_TAG', description: 'Deploy Tag')
    }

    stages {

        stage('Test') {

            options {
                timeout(time: 250, unit: 'SECONDS')
            }

            when {
                expression {
                    params.DEPLOY_TAG == ''
                }
            }

            steps {
                dir('shopping-cart-v2') {
                    sh './mvnw clean test'
                }
            }
        }

        stage('Build Image') {

            environment {
                QUAY = credentials('QUAY_USER')
            }

            when {
                expression {
                    params.DEPLOY_TAG == ''
                }
            }

            steps {
                dir('shopping-cart-v2') {
                    sh './scripts/include-container-extensions.sh'
                    sh '''
                        ./scripts/build-and-push-image.sh \
                        -u ${QUAY_USR} \
                        -p ${QUAY_PSW} \
                        -b ${BUILD_NUMBER}
                    '''
                }
            }
        }

        stage('Deploy') {

            environment {
                QUAY = credentials('QUAY_USER')
            }

            steps {
                dir('shopping-cart-v2') {
                    script {

                        def tagToDeploy = 'BUILD-${BUILD_NUMBER}'

                        if (params.DEPLOY_TAG != null && params.DEPLOY_TAG != '') {

                            tagToDeploy = params.DEPLOY_TAG

                            def status = sh(
                                script: './scripts/tag-exists-in-quay.sh ${QUAY_USR}/do400-recover ${tagToDeploy}',
                                returnStatus: true
                            )

                            if (status != 0) {
                                error('Tag not found in quay.')
                            }

                        }
                        
                        sh '''
                                ./scripts/deploy-image.sh \
                                    -n ${APP_NAMESPACE} \
                                    -u ${QUAY_USR} \
                                    -t ${tagToDeploy}
                            '''
                        
                    }
        
                }
            }
        }

    }

}