pipeline{
    agent any
    stages{

        // Add the "Deploy" stage here
        stage("Deploy"){
            steps{
                sh '''
                    oc project qzjkdo-deploy-strategies
                    oc start-build greeting-service --follow --wait
                '''
            }
        }
    }
}
