pipeline{
    agent{
        label "nodejs"
    }
    stages{
        stage('Switch to project dir'){
            steps{
                sh "cd greeting-service"
            }
        }

        stage("Install dependencies"){
            steps{
                sh "npm ci"
            }
        }

        stage("Check Style"){
            steps{
                sh "npm run lint"
            }
        }

        stage("Test"){
            steps{
                sh "npm test"
            }
        }

        // Add the "Deploy" stage here
        stage("Deploy"){
            steps{
                sh '''
                    oc project qzjkdo-deploy-strategies
                    oc start-build greeting-service --follow --wait
                '''
            }
        }
    }
}
